## Write a Numpy program to compute the multiplication of two given matrixes

In [3]:
import numpy as np
x = [[8, 7], [4, 6]]
y = [[3, 5], [2, 7]]
result1 = np.dot(x, y)


In [4]:
print(result1)

[[38 89]
 [24 62]]


## Write a NumPy program to compute the determinant of a given square array

In [5]:
a = np.array([[1, 0], [1, 2]])

print(a)

[[1 0]
 [1 2]]


## Write a NumPy program to compute the cross product of two given vectors

In [14]:
x = [[1, 0], [0, 1]]
y = [[1, 2], [3, 4]]
result1 = np.cross(y, x)

In [16]:
print(result1)

[-2  3]


## Write a NumPy program to compute the condition number of a given matrix

In [18]:
mat = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])
print(mat)

[[ 1  0 -1]
 [ 0  1  0]
 [ 1  0  1]]


## Write a NumPy program to compute the inverse of a given matrix

In [19]:
m = np.array([[1,2],[3,4]])

In [20]:
result =  np.linalg.inv(m)
print(result)

[[-2.   1. ]
 [ 1.5 -0.5]]
